// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orpmmqtuafmpttnjabqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycG1tcXR1YWZtcHR0bmphYnF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjExNDEsImV4cCI6MjA1OTM5NzE0MX0.YvEbCZd5MqOova99XeBlcY7Fjs8Bic3orJ8HZZTlCgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);